### ISSUE TITLE
logout()

### ISSUE THREAD

**Issue by smunx** [jbreckmckye/electron-auth0-login#10]
I am calling the logout() while closing the app. But the next time again when I open the app it is not asking for a login. The logout() should remove the the all the token data right ?
I have also set the useRefreshTokens: true

Thanks,

**Comment by jbreckmckye** [comment]
Yes, it should do. The only way it wouldn't is if something went wrong calling node-keytar:

```
 public async logout() {
        this.tokenProperties = null;
        if (this.useRefreshToken) {
            await keytar.deletePassword(this.config.applicationName, 'refresh-token');
        }
    }
```

What version of keytar (and the plugin) are you using? Can you share your `package.json`?

**Comment by smunx** [comment]
Yes I am using the keytar plugin and the version is 5.1.0.
My package.json is very basic. The only other package I have is electron (6.0.9).

**Comment by jbreckmckye** [comment]
Are any errors logged when you call `logout()`?

**Comment by ianjennings** [comment]
I've noticed that `node-keytar` is no longer available and seems to be renamed `keytar`

**Comment by jbreckmckye** [comment]
@ianjennings Okay, I might have time to release a new version this week. Or I can accept a PR with an updated dependency.

**Comment by jbreckmckye** [comment]
Docs are updated to say `keytar` instead of `node-keytar`. Sorry I forgot about this.
