### ISSUE TITLE
Feature Request: Config access to BrowserWindow object

### ISSUE THREAD

**Issue by malammar** [jbreckmckye/electron-auth0-login#11]
Our application has a certain style and UX standards that we need to follow. The login window that this package has a hard-coded configuration that doesn't allow us to hide the titlebar, chrome, or specify the size.

Ideally, we'd like access to a subset of the BrowserWindow parameters and have those passed down through the standard config object in a property called "browserWindowConfig".

**Comment by jbreckmckye** [comment]
That would definitely be possible. I could also expose the browserWindow itself?

I'm a bit busy today but might have time later in the week. Alternatively I'm happy to accept a PR? The class itself is fairly [short](https://github.com/jbreckmckye/electron-auth0-login/blob/master/src/index.ts#L12).

**Comment by jbreckmckye** [comment]
@malammar Would this PR work for you? https://github.com/jbreckmckye/electron-auth0-login/pull/12

**Comment by jbreckmckye** [comment]
#12 is merged now.
