### ISSUE TITLE
Uncaught TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by samuelkampf** [jbreckmckye/electron-auth0-login#15]
type error with version 1.3.0 
`Uncaught TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined`

**Comment by jbreckmckye** [comment]
Could you post a stacktrace? I'm curious where this could be coming from

**Comment by samuelkampf** [comment]
it may be because im using angular its not possible to import this into a component is it?

**Comment by danteata** [comment]
I get the same error as well.

```
Uncaught TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:112)
    at dirname (path.js:1129)
    at Object.exports.findPackage (index.js:209)
    at Object.exports.register (index.js:295)
    at Object.eval (index.js:19)
    at eval (index.js:158)
    at Object../node_modules/electron-auth0-login/dist/index.js (renderer.dev.dll.js:12965)
    at __webpack_require__ (renderer.dev.dll.js:21)
    at Object../node_modules/electron-auth0-login/dist/index.js (index.js from dll-reference renderer:1)
    at __webpack_require__ (bootstrap:726)
NodeError @ internal/errors.js:216
validateString @ internal/validators.js:112
dirname @ path.js:1129
exports.findPackage @ index.js:209
exports.register @ index.js:295
eval @ index.js:19
eval @ index.js:158
./node_modules/electron-auth0-login/dist/index.js @ renderer.dev.dll.js:12965
__webpack_require__ @ renderer.dev.dll.js:21
./node_modules/electron-auth0-login/dist/index.js @ index.js from dll-reference renderer:1
__webpack_require__ @ bootstrap:726
fn @ bootstrap:100
(anonymous) @ Routes.js:3
./app/Routes.js @ renderer.dev.js:960
__webpack_require__ @ bootstrap:726
fn @ bootstrap:100
(anonymous) @ Root.js:5
./app/containers/Root.js @ renderer.dev.js:12569
__webpack_require__ @ bootstrap:726
fn @ bootstrap:100
(anonymous) @ index.js:4
./app/index.js @ renderer.dev.js:12663
__webpack_require__ @ bootstrap:726
fn @ bootstrap:100
0 @ only-dev-server.js:102
__webpack_require__ @ bootstrap:726
(anonymous) @ bootstrap:793
(anonymous) @ bootstrap:793
```

**Comment by jbreckmckye** [comment]
@danteata Do you get the same issue with v1.1.0? I'm wondering whether this is a problem with the latest build

**Comment by samuelkampf** [comment]
The problem only occurs if you use it inside an app if you import and use
it in main it works but anywhere else it errors

**Comment by jbreckmckye** [comment]
Ah. Thanks for that insight @samuelkampf. Yeah, there is a line about this in the readme, but it's a bit hidden -

> In a module available to your main process code (e.g. auth.ts): `{setup code }`

I will try and make this a bit clearer.

**Comment by samuelkampf** [comment]
yeah thats the only downfall about it there is no way to call it inside of
angular. I ended up switching over to firebase which imo is much better
than auth0's aio solution

**Comment by samuelkampf** [comment]
one work around is to serve your entire electron app from express then u
can call from localhost using auth0 lock etc

**Comment by danteata** [comment]
Thanks for clarifying @jbreckmckye. Using in the main process code worked.

**Comment by jbreckmckye** [comment]
I've updated the docs to make this a bit more obvious.
