### ISSUE TITLE
Helpless

### ISSUE THREAD

**Issue by hjertefolger** [jbreckmckye/electron-auth0-login#19]
Hello guys,

this is not particularly an issue, just mine. You should delete this later guys.

I would like to kindly ask you if you could help me to implement your solution to basic Electron Quick Start so I could learn and understand how to do it in most simple/basic way. I've tried, but failed in every way:

1. I've created auth.js, pasted your code and filled Auth0 credentials
* and this is literally how far I've got

- I couldn't use "import" in main.js (throwing me an error with can't use import outside a module)
- don't know how to implement auth.js into main process (BrowserWindow) so there will be Auth0 login loaded just after app launch (if I get it correctly)
- is it also possible to launch login by clicking some "Log in" button and redirect users to other screen/html file after success? (something like protected route in react).

Thank you very much in advance, for your patience, effort and any help in this case! All the best, Tomas

**Comment by jbreckmckye** [comment]
Hello Tomas, sounds like you're having problems with your bundler and modules?

For instance, if you can't use import in main.js, that suggests that either you need to use an Electron version whose Node runtime handles ES6 modules, or you need your transpilation stack to compile ES6 modules to SystemJS style imports instead.

It also sounds like you're struggling with Electron more generally. For instance, the main process in Electron is the Node thread, not the browser window. You may be trying to initialise the plugin in the wrong place.

Either way it doesn't sound like a bug with the library itself, so I'm going to close the issue, but the thread will remain open in case you have any further questions.

**Comment by ArsenicBismuth** [comment]
Have a massive trouble myself forcing to use ES6. Node doesn't support it directly, and shouldn't be considered a default option.

**Comment by jbreckmckye** [comment]
@ArsenicBismuth Are you talking about ES modules? (ES6 comprises several things) You do not have to use ES modules with this library, as it is compiled to CommonJS format.

**Comment by jbreckmckye** [comment]
@ArsenicBismuth Are you talking about ES modules? "ES6" comprises several things.

If so, you do not need to use ES modules with this library, as it is distributed in CommonJS format ([config](https://github.com/jbreckmckye/electron-auth0-login/blob/master/tsconfig.json#L4))

**Comment by jbreckmckye** [comment]
I think I understand the issue now: I suspect you have both used the TypeScript examples in plain JavaScript, which is causing you trouble due to not using `.mjs` files.  I've added a comment to the examples to make this clearer.
