### ISSUE TITLE
Access Denied using Machine to machine app from auth0

### ISSUE THREAD

**Issue by Luis92pe** [jbreckmckye/electron-auth0-login#2]
I have the following error: when I create an app in auth0 of type 'machine to machine' the method getToken I return a **401** with **access denied**. On the other hand, if I use a 'native' type app if it works for me, why is this?

**Comment by jbreckmckye** [comment]
If I recall correctly, 'machine to machine' is intended for backend services speaking to other backend services. Think of a Node/Express app that services a frontend SPA by calling internal Java microservices - that would be a machine-to-machine transaction.

I will add a line to the README telling users to set their apps up as 'native' instead.

**Comment by Luis92pe** [comment]
mm ok ok, I understand. Thanks for the clarification.
