### ISSUE TITLE
Types issue

### ISSUE THREAD

**Issue by ceremonious** [jbreckmckye/electron-auth0-login#29]
Hi, thank you for creating this library! I saw that you released v2 right as I was looking to integrate Auth0 & Electron.

I'm getting a type error when trying to call getToken() because I'm not passing in any arguments. 

The library seems to be generating the following types for the auth object (This is the index.d.ts file in node_modules/electron-auth0-login/dist):

```
import { Config } from './types';
declare const _default: (config: Config) => {
    getToken: (input: unknown) => Promise<string>;
    isLoggedIn: (input: unknown) => boolean;
    login: (input: unknown) => Promise<string>;
    logout: (input: unknown) => Promise<void>;
};
export = _default;
```

**Comment by jbreckmckye** [comment]
Thanks for the report. I'll take a look at this later today (maybe tonight).

**Comment by jbreckmckye** [comment]
@ceremonious I've just pushed version 2.0.1, which should fix the types.

**Comment by ceremonious** [comment]
Thank you!

**Comment by jbreckmckye** [comment]
Let me know if you have any further issues
