### ISSUE TITLE
Auth0 configuration API doesn't specify database connection for auth0 application

### ISSUE THREAD

**Issue by ahmeddwaheed** [jbreckmckye/electron-auth0-login#37]
The config object in the `types.ts` file doesn't have a parameter for the db connection of auth0 and it should be included as the auth0 API documentation shows in their official documentation
![Screenshot from 2022-06-13 15-15-44](https://user-images.githubusercontent.com/29347350/173362165-a8690651-a89c-4100-b8b0-61535d510d89.png)

as shown in the config of auth0 object it doesn't have a connection option to determine which db the user can use if a single application is using multiple
```js
// Details of the Auth0 application
auth0: {
    // Get these from your Auth0 app dashboard
    audience: string,
    clientId: string,
    domain: string,
    // This will be custom to your application, e.g. 'given_name profile'
    scopes: string
},
```

**Comment by ahmeddwaheed** [comment]
I added this pull request to fix this issue https://github.com/jbreckmckye/electron-auth0-login/pull/38

**Comment by jbreckmckye** [comment]
Hi Ahmedd, I'm not really familiar with this parameter. I don't use Auth0 a great deal nowadays.

Can you explain why someone using this library would need to supply it?

**Comment by ahmeddwaheed** [comment]
Hi Jimmy, Auth0 applications can be connected to multiple database connections not only one, the package doesn't provide a way to select which database connection the user would like to use to authenticate users so it uses the default connection always

Here's an example of an application that is authorized to use two different database connections on Auth0
![Screenshot from 2022-06-13 16-19-07-Copy](https://user-images.githubusercontent.com/29347350/173375842-84a9494e-a142-49e3-bca3-19c571c98836.png)
![Screenshot from 2022-06-13 16-19-27-Copy](https://user-images.githubusercontent.com/29347350/173375868-790dc431-bb78-46e0-a9fc-22473ddc60ec.png)

To be able to select a database connection to use you need to provide a `connection` parameter and Auth0 will authenticate the token against the database you specified

**Comment by ahmeddwaheed** [comment]
Here's the implementation for auth0-spa-js which has the `connection` variable to be used if needed, [line](https://github.com/auth0/auth0-spa-js/blob/4b48762d382e0e2d76c567da43c05a28bcd1f7ce/src/global.ts#L78)

**Comment by jbreckmckye** [comment]
Hi Ahmedd, thanks for getting back to me.

I can understand now what your database feature is about - it's having multiple repositories within your Auth0 account for users in different 'contexts'.

Do you know where it's documented that you can key these using the `connection` field? I can see that these can be used to specify social login providers, but not that these are used for databases too.

One thing I would need to check is that if a social login provider is passed, this doesn't break the auth flow. Right now that works on parsing the URL after a navigation event. If it doesn't work I'd probably need to add a warning in the documentation.

**Comment by ahmeddwaheed** [comment]
Based on the official documentation of Auth0 APIs#login (social section) https://auth0.com/docs/api/authentication#login indicates that the `connection` field is used with users from different social providers ie; [`github`, `twtitter`, `google-oauth2`] and these providers, in the end, are using different databases under these names and you can navigate users with the `connection` field. This is the same idea of using a non-social database/s which is explained in this [section](https://auth0.com/docs/api/authentication#change-password) which says: 

> connection: (REQUIRED) | The name of the database connection configured to your client.

Which didn't explain that your connection must be a social one.

Also the `Signup` [section](https://auth0.com/docs/api/authentication#signup), it says that you can use the `connection` field as the 
> The name of the database configured to your client.

But it's not specific to be used only in this situation. It's not explained directly but with this [reference](https://auth0.com/docs/libraries/lock/selecting-from-multiple-connection-options) too, which says
> In Auth0, you can associate different connections (methods of authentication) to specific applications, or directly to a tenant (as [domain connections](https://auth0.com/docs/authenticate/identity-providers/promote-connections-to-domain-level)). When a user logs in, one of these connections will need to be selected as the one to use.

Also, I tested the change in different scenarios for a project I'm working on. I needed to make sure that it will be backward compatible with package users so this is why the field isn't required in `/authorize` requests as while it is optional the connection fallbacks to the default database when you don't specify it.

**Comment by jbreckmckye** [comment]
> Based on the official documentation of Auth0 APIs#login (social section) https://auth0.com/docs/api/authentication#login indicates that the connection field is used with users from different social providers ie; github, twtitter, google-oauth2

Indeed it does. One concern I have is whether specifying a social provider will break the auth code mechanism. We rely on the browser window finishing in a state with the auth code serialised into the URL. So I would need to check this.

> and these providers, in the end, are using different databases under these names

This has been the part that has thrown me off. You've written about this as though social signin is implemented in the same way as connecting to e.g. some MySQL instance exposed on the internet. Hence the confusion.

It might be that the string can be used for either social login or set up database connections. But "in the end" I am doubtful they have the same implementation. So when you submitted an issue and PR talking about 'databases' in the context of something documented for social login, I was a little surprised.

It sounds like what you mean, is that custom database connections are named via a developer-supplied key, and that key can be passed as the `connection` field, along with the names of social login providers. Is that correct?

The reason I want to check is that although `connection` is used for both purposes, I've yet to see API documentation that confirms they are used for both in the `/authorize` request.

> Also, I tested the change in different scenarios for a project I'm working on.

And did you find that `connection` would discriminate between users in one database connection, and another?

**Comment by ahmeddwaheed** [comment]
This is not related to any external databases on the internet, the database terminology I frequently use refers to Auth0 databases. Auth0 exposes the developer to switch connection to a social database or a non-social database by `connection` field in the authorization flow, a non-social database is like the default one created by Auth0 `UserName-Password-Authentication` or any database of your creation inside Auth0 from `+ CREATE DB CONNECTION` button

<img width="752" alt="dashboard-connections-database-list__1_" src="https://user-images.githubusercontent.com/29347350/173831739-954f87ee-aece-44e3-843b-27bb8b394377.png">
It also could be a custom database created by a developer-supplied key under any name within Auth0 so that users can be authenticated via your login scripts.
<br/><br/>

FYI; I tested the auth flow with a `connection` set to social apps like `google-oauth2`, and it's working fine

![Screenshot from 2022-06-15 15-57-47](https://user-images.githubusercontent.com/29347350/173845851-192f3a14-5684-48d0-9654-c6fe0f155517.png)


In the end, what I mean is that you will need the `connection` field to do that switch to authenticate users based on any connection you might have wether a social or non-social one as long as it's within your Auth0 connections

**Comment by jbreckmckye** [comment]
Cool, this sounds pretty straightforward then. When you used the social connection, did the library get the auth token OK?

**Comment by ahmeddwaheed** [comment]
Yes, it's working fine the same as the normal login flow

**Comment by jbreckmckye** [comment]
@ahmeddwaheed Actually, I just realised something - we already support passing arbitrary parameters to the /authorize call

You just need to pass some `login.authorizeParams` into the config. These are then spread onto the query Paramus.

See here: https://github.com/jbreckmckye/electron-auth0-login/blob/master/src/adapters/authWindow.ts#L42

This is documented here: https://github.com/jbreckmckye/electron-auth0-login/blob/master/docs/setup.md#configuration-options

I was wondering why we didn't just let the user pass custom parameters...

**Comment by ahmeddwaheed** [comment]
I tested it and it works, I think I missed that too, my bad. Anyway thank you for your time and interest to crack this issue up, you can close the issue now

**Comment by jbreckmckye** [comment]
No worries, I completely forgot about this! It was a feature I must have ported during the rewrite, without remembering
