### ISSUE TITLE
Can't load content from Auth0 login page: net::ERR_BLOCKED_BY_RESPONSE

### ISSUE THREAD

**Issue by marcosvidal** [jbreckmckye/electron-auth0-login#40]
When the browserwindow opens and goes to the auth0 login URL, it tries to use a script (lock.min.js) that fails to load. The complete error is:

`Failed to load resource: net::ERR_BLOCKED_BY_RESPONSE.NotSameOriginAfterDefaultedToSameOriginByCoep`

Obviously, this makes page unusable. Any idea why this might be happening?

Any help to point me in the right direction would be much appreciated.

**Comment by jbreckmckye** [comment]
At first glance this seems to be something to do with [Cross Origin Embedder Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Embedder-Policy)

**Comment by marcosvidal** [comment]
Thanks for your help. I figured that out and solved the issue by changing the headers to accept content from auth0.

**Comment by jbreckmckye** [comment]
Can you provide more details? What do you mean by "changing the headers"? In which request? And to what values?
