### ISSUE TITLE
NPM installation broken 'Please verify that the package.json has a valid "main" entry'

### ISSUE THREAD

**Issue by roberttolton** [jbreckmckye/electron-auth0-login#41]
Hi,

It seems like the `dist` folder is missing from what's installed by NPM, and therefore trying to boot my app results in:

```
Error: Cannot find module '/Users/XX/Documents/web-dev/XX/XX/node_modules/electron-auth0-login/dist/index.js'. Please verify that the package.json has a valid "main" entry
```

Any ideas?
Thanks!

**Comment by jbreckmckye** [comment]
Ah, that's embarrassing. Try v2.0.5.
(I need to automate the build process to stop this from happening)

**Comment by roberttolton** [comment]
Amazing, thank you @jbreckmckye !
