### ISSUE TITLE
Cannot find name 'Config' in index.d.ts

### ISSUE THREAD

**Issue by markmakes** [jbreckmckye/electron-auth0-login#6]
Using Angular 8.2 and Electron 6.0.2

ERROR in ../node_modules/electron-auth0-login/dist/index.d.ts:5:25 - error TS2304: Cannot find name 'Config'.

5     constructor(config: Config);

Any ideas on the typings? Do I need to change something in my Angular config?

**Comment by jbreckmckye** [comment]
That's strange. What's your tsconfig like?

I wonder if moving `Config` from an ambient to an exported type would help. I can try tonight.

**Comment by jbreckmckye** [comment]
(Sorry for the delay in responding - I didn't have this repo on my watchlist)

**Comment by markmakes** [comment]
No worries @jbreckmckye - here's our tsconfig

```
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "allowSyntheticDefaultImports": true,
    "module": "esnext",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "es2015",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2018",
      "dom",
      "es2018.promise"
    ]
  },
  "allowJs": true
}
```

**Comment by jbreckmckye** [comment]
Sorry, I forgot about this. Did you end up fixing it?

**Comment by samuelkampf** [comment]
all you have todo is take the interface from the typings and add it to the index file where the error is occuring thats how i fixed it atleast

**Comment by samuelkampf** [comment]
but then it will error out with `Uncaught TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined`

**Comment by samuelkampf** [comment]
unless i put it in main.ts if i put it in any component.ts it errors with the error above

**Comment by samuelkampf** [comment]
any help with this would be greatly appreciated

**Comment by samuelkampf** [comment]
i fixed it so i created the interface in the config initialized like normal in main then i run the following code in my serve this will prevent the app from opening if not logged in

```
  if (serve) {
    require('electron-reload')(__dirname, {
      electron: require(`${__dirname}/node_modules/electron`)
    });
    win.loadURL('http://localhost:3000');
  } else {
    auth.getToken().then(res => {
      if(!res){ return } else {
        win.loadURL(url.format({
          pathname: path.join(__dirname, 'dist/index.html'),
          protocol: 'file:',
          slashes: true
        }))
      }
    } )

  }
```

**Comment by samuelkampf** [comment]
great job btw @jbreckmckye

**Comment by samuelkampf** [comment]
i know that there is probably a better way of fixing that config issue but it was just on the fly and a quick fix

**Comment by jbreckmckye** [comment]
In the latest version (1.3.0) there are no ambient types, so you shouldn't have this issue any more.

**Comment by samuelkampf** [comment]
i dont see version 1.3.0 only 1.1.0
